#!/usr/bin/env bash
# ============================================================
# Xyra Voice — Kamailio secrets setup
#
# Creates infra/kamailio/secrets/kamailio-db.cfg with the
# DBURL needed by Kamailio to authenticate SIP users against
# Supabase.
#
# Run this on the VPS, NOT in the repo on your laptop.
# ============================================================
set -euo pipefail

cd "$(dirname "$0")"

SECRETS_DIR="kamailio/secrets"
SECRETS_FILE="$SECRETS_DIR/kamailio-db.cfg"

mkdir -p "$SECRETS_DIR"

if [ -f "$SECRETS_FILE" ]; then
  echo "⚠  $SECRETS_FILE already exists. Backing up to $SECRETS_FILE.bak"
  cp "$SECRETS_FILE" "$SECRETS_FILE.bak"
fi

echo
echo "─── Xyra Voice — Kamailio DB connection setup ───"
echo
echo "Default Supabase host: db.bfrnuhdihiidchsozdxm.supabase.co"
read -rp "Supabase DB host [db.bfrnuhdihiidchsozdxm.supabase.co]: " DB_HOST
DB_HOST=${DB_HOST:-db.bfrnuhdihiidchsozdxm.supabase.co}

read -rp "kamailio_ro Postgres password: " -s KAM_PASS
echo

# URL-encode special characters in password (basic — handles most cases)
KAM_PASS_ENC=$(python3 -c "import urllib.parse,sys; print(urllib.parse.quote(sys.argv[1], safe=''))" "$KAM_PASS")

cat > "$SECRETS_FILE" <<EOF
# Auto-generated by setup-kamailio-secrets.sh
# Do not commit this file.

#!define DBURL "postgres://kamailio_ro:${KAM_PASS_ENC}@${DB_HOST}:5432/postgres?sslmode=require"
EOF

chmod 600 "$SECRETS_FILE"

echo
echo "✅ Wrote $SECRETS_FILE"
echo
echo "Now testing the connection..."

# Test with psql if available
if command -v psql >/dev/null 2>&1; then
  if PGPASSWORD="$KAM_PASS" psql -h "$DB_HOST" -U kamailio_ro -d postgres -c "select count(*) from public.sip_users;" 2>&1; then
    echo "✅ Connection successful — kamailio_ro can read sip_users"
  else
    echo "❌ Connection failed. Check the password and that you ran 004_kamailio_role.sql in Supabase."
    exit 1
  fi
else
  echo "(psql not installed, skipping connection test)"
  echo "Install with: apt install -y postgresql-client"
fi

echo
echo "Next: docker compose restart kamailio"
